FROM quay.io/toolbx-images/alpine-toolbox

RUN set -eux; \
	apk upgrade --no-cache; \
	apk add --no-cache font-terminus font-inconsolata font-dejavu font-noto font-noto-cjk font-awesome font-noto-extra; \
	apk add --no-cache firefox;
