FROM ghcr.io/bonjour-py/toolbox/kali

RUN set -eux; \
	apt update; \
	apt upgrade -y; \
	rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
	apt update; \
	apt install -y kali-system-cli; \
	apt clean; \
	rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
	apt update; \
	apt install -y firefox-esr; \
	rm -rf /var/lib/apt/lists/*;

# Chinese
RUN set -eux; \
	apt update; \
	apt install -y locales; \
	apt clean; \
	rm -rf /var/lib/apt/lists/*; \
	\
	ln -sf ../usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
	\
	sed -i -e 's@# zh_CN.UTF-8@zh_CN.UTF-8@' /etc/locale.gen; \
	locale-gen; \
	echo 'LANG=zh_CN.UTF-8' | tee /etc/locale.conf;

# deepin-wine
RUN wget -O- https://deepin-wine.i-m.dev/setup.sh | sh;
# WXwork
RUN set -eux; \
	\
	echo '#' | tee /etc/apt/preferences.d/com.qq.weixin.work.deepin.pref; \
	echo 'Package: libsane1' | tee -a /etc/apt/preferences.d/com.qq.weixin.work.deepin.pref; \
	echo 'Pin: release l=deepin-wine' | tee -a /etc/apt/preferences.d/com.qq.weixin.work.deepin.pref; \
	echo 'Pin-Priority: 600' | tee -a /etc/apt/preferences.d/com.qq.weixin.work.deepin.pref; \
	echo | tee -a /etc/apt/preferences.d/com.qq.weixin.work.deepin.pref; \
	echo 'Package: libsane-common' | tee -a /etc/apt/preferences.d/com.qq.weixin.work.deepin.pref; \
	echo 'Pin: release l=deepin-wine' | tee -a /etc/apt/preferences.d/com.qq.weixin.work.deepin.pref; \
	echo 'Pin-Priority: 600' | tee -a /etc/apt/preferences.d/com.qq.weixin.work.deepin.pref; \
	\
	apt update; \
	apt install -y com.qq.weixin.work.deepin; \
	apt clean; \
	rm -rf /var/lib/apt/lists/*; \
	\
	sed -i -e 's@7z x "$APPDIR/$APPTAR" -o"$1"@7z x "$APPDIR/$APPTAR" -o"$1" || true@g' /opt/deepinwine/tools/run.sh /opt/deepinwine/tools/run_v2.sh /opt/deepinwine/tools/run_v3.sh /opt/deepinwine/tools/run_v4.sh; \
	\
	echo '#!/usr/bin/bash' | tee /usr/local/bin/com.qq.weixin.work.deepin.sh; \
	echo 'export XDG_SESSION_TYPE=x11' | tee -a /usr/local/bin/com.qq.weixin.work.deepin.sh; \
	echo 'export DISPLAY=:0' | tee -a /usr/local/bin/com.qq.weixin.work.deepin.sh; \
	echo 'export XMODIFIERS=@im=ibus' | tee -a /usr/local/bin/com.qq.weixin.work.deepin.sh; \
	echo '/opt/apps/com.qq.weixin.work.deepin/files/run.sh' | tee -a /usr/local/bin/com.qq.weixin.work.deepin.sh; \
	chmod +x /usr/local/bin/com.qq.weixin.work.deepin.sh;

RUN set -eux; \
	apt update; \
	apt install -y \
		python-is-python3 \
		python3-requests \
		python3-yaml \
		python3-flask \
	; \
	apt clean; \
	rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
	apt update; \
	apt install -y cargo; \
	apt clean; \
	rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
	apt update; \
	apt install -y golang; \
	apt clean; \
	rm -rf /var/lib/apt/lists/*;