name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-toolbox:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        name: 
          - deepin-wine
          - kali
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/toolbox/{{ matrix.name }}
          tags: type=raw,value=latest,enable={{ is_default_branch }}
      - name: Buildah Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          oci: true
          layers: true
          context: toolbox/{{ matrix.name }}
          containerfiles: toolbox/{{ matrix.name }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push To ghcr.io
        if: github.event_name != 'pull_request'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-toolbox-deepin-wine:
    runs-on: ubuntu-latest
    needs: build-toolbox
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        name: 
          - wxwork
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/toolbox/deepin-wine/{{ matrix.name }}
          tags: type=raw,value=latest,enable={{ is_default_branch }}
      - name: Buildah Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          oci: true
          layers: true
          context: toolbox/deepin-wine/{{ matrix.name }}
          containerfiles: toolbox/deepin-wine/{{ matrix.name }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push To ghcr.io
        if: github.event_name != 'pull_request'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-work:
    runs-on: ubuntu-latest
    needs: build-toolbox
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/work
          tags: type=raw,value=latest,enable={{ is_default_branch }}
      - name: Buildah Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          oci: true
          layers: true
          context: work
          containerfiles: work/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push To ghcr.io
        if: github.event_name != 'pull_request'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
