name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-base:
    strategy:
      matrix:
        name: 
          - toolbox/kali
          - toolbox/deepin-wine
          - toolbox/firefox
          - owasp/benchmark
    uses: ./.github/workflows/container.yml
    with:
      name: ${{ matrix.name }}

  build-deepin-wine:
    needs: build-base
    strategy:
      matrix:
        name: 
          - wxwork
    uses: ./.github/workflows/container.yml
    with:
      name: toolbox/deepin-wine/${{ matrix.name }}