name: Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: 
          - toolbox/deepin-wine
          - toolbox/kali
    uses: ./.github/workflows/container.yml
    with:
      name: ${{ matrix.name }}

  build-toolbox-deepin-wine:
    runs-on: ubuntu-latest
    needs: build-base
    strategy:
      matrix:
        name: 
          - wxwork
    uses: ./.github/workflows/container.yml
    with:
      name: toolbox/deepin-wine/${{ matrix.name }}

  build-work:
    runs-on: ubuntu-latest
    needs: build-base
    uses: ./.github/workflows/container.yml
    with:
      name: work