name: Container

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.name }}
      - name: Cache image storage
        uses: actions/cache@v4
        with:
          key: default
          path: |
            ~/.local/share/containers/storage
      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.name }}
          tags: type=raw,value=latest,enable={{ is_default_branch }}
      - name: Buildah Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          oci: true
          layers: true
          context: ${{ inputs.name }}
          containerfiles: ${{ inputs.name }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          extra-args: |
            --pull=newer
      - name: Push To ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
